#ifndef _SOCKETS_H_
#define _SOCKETS_H_ 1



#include <vector>
#include <memory>
#include <thread>
#include <mutex>
#include <condition_variable>
#include <map>
#include <queue>
#include <chrono>



struct sockaddr_in; // forward declarations, avoids including winsock in header
//struct SOCKET;
typedef unsigned __int64 SOCKET ; // has to match sockettype in winsock2

class PacketReceiver ;

// Structure to hold queued outgoing packet
struct PendingPacket {
	std::vector<char> data;
	std::shared_ptr<sockaddr_in> addr;
};


// An abstract socket that could be either client or server
class Socket {
	public:
		// Send data through this socket
		// Returns if data seems to have sent (we can't know now if it arrived)
		virtual bool send(int receiver_id, const std::vector<char>& data) = 0;

		// close all connections in this socket and stop allowing new ones if applicable
		virtual void close() = 0;
	
		//Set the object that will get packets when they are sent to this socket
		virtual void setPacketReceiver(PacketReceiver* receiver) = 0 ;

		//Loops to make sure all of the bytes go through on a send (for TCP only)
		static bool sendAll(SOCKET socket, const char* source, int num_bytes);

		//Loops to make sure all of the bytes get read on a recv (for TCP only)
		static bool recvAll(SOCKET socket, char* destination, int num_bytes);
};

//An abstract interface that can be overwridden to get socket data forwarded to custom classes
class PacketReceiver {
public:

	//Called when a packet is received
	virtual void receivePacket(int sender_id, const std::vector<char>& data) = 0;
	
	//Called when a connection is established, 
	//sender_id is generated by the socket and can be used to identify recieved packet sources or send data back through the socket
	virtual void onSocketConnect(int sender_id) = 0 ;

	//Called when a connection is closed, either remotely or because the socket holding it was closed
	virtual void  onSocketClose(int sender_id) = 0 ;

};

//A wrapper for a packet receiver that simulates lag by holding packets to deliver
//Careful to not allocate this on the stack as it creates a thread on itself, use a shared_ptr
class SlowPacketReceiver: public PacketReceiver {
public:
	
	

	struct SlowPacket{
		int sender = -1 ;
		std::chrono::high_resolution_clock::time_point arrival_time ;
		std::vector<char> data ;
		SlowPacket(int s, std::chrono::high_resolution_clock::time_point a, const std::vector<char>& d){
			sender =s ;
			arrival_time = a;
			data = d ;
			if(d.size() == 0){
				printf("completely empty packet!?\n");
			}
		}
	};

	std::queue<std::shared_ptr<SlowPacket>> packets ;

	SlowPacketReceiver(PacketReceiver* r, int micros_of_delay, int micros_of_jitter) ;

	//Called when a packet is received
	void receivePacket(int sender_id, const std::vector<char>& data) override;

	//Called when a connection is established, 
	//sender_id is generated by the socket and can be used to identify recieved packet sources or send data back through the socket
	void onSocketConnect(int sender_id) override;

	//Called when a connection is closed, either remotely or because the socket holding it was closed
	void  onSocketClose(int sender_id) override;



	void stop();

private:
	PacketReceiver* receiver;
	std::thread thread;
	std::recursive_mutex lock;
	int lag_micros = 0;
	int jitter_micros = 0 ;
	int next_jitter = 0 ;
	bool stopped = false;
	//runs the thread to deliver the packet withthe delay
	void run();
};


class TestPacketReceiver : public PacketReceiver {
public:
	bool is_server = false;
	Socket* socket ;

	TestPacketReceiver(bool server, Socket* socket){
		is_server = server ;
		this->socket = socket ;
	}

	//Called when a packet is received
	void receivePacket(int sender_id, const std::vector<char>& data) override{
		std::string text(data.data(),data.size()) ;
		printf("Got packet: %s\n", text.c_str()) ;
	}

	//Called when a connection is established, 
	//sender_id is generated by the socket and can be used to identify recieved packet sources or send data back through the socket
	void onSocketConnect(int sender_id) override{
		printf("Connected to %d\n", sender_id) ;
		if(is_server){
			std::string text = "Hello from a server with a test packet reciever" ;
			std::vector<char> data(text.data(), text.data()+text.size()) ;
			socket->send(sender_id, data) ;
		}
	}
	

	//Called when a connection is closed, either remotely or because the socket holding it was closed
	void  onSocketClose(int sender_id) override{
		printf("Disconnected from %d\n", sender_id);
	}

	void stop();

};


class UDPServerSocket : public Socket{
public:
	static inline int packet_wait_micros = 5000; // microseconds to wait for a packet before checking the send queue
		
	
	//Open a UDP socket on the given port
	// Returns if apparently successful
	bool open(int port);

	// Send data through this socket
	// Returns if data seems to have sent (we can't know now if it arrived)
	bool send(int receiver_id, const std::vector<char>& data) override;

	// close all connections in this socket and stop allowing new ones if applicable
	void close() override;

	//Set the object that will get packets when they are sent to this socket
	void setPacketReceiver(PacketReceiver* receiver) override;
	
	~UDPServerSocket();
	
private:
	std::shared_ptr<SOCKET> socket;
	int port = 0;
	std::map<int, std::shared_ptr<sockaddr_in>> clients; // connection id -> client address
	std::thread thread ; // nonblocking socket has its own thread to wait for any packets
	std::recursive_mutex lock ; // used to protect against modifying the socket while packets are being received
	bool stop = false ; // tells the thread to stop at the next chance
	int next_client_id = 0 ;
	std::queue<PendingPacket> send_queue;
	PacketReceiver* packet_receiver;
	char buffer[32768] = {};

	// asynchronous method to catch packets and deliver them to PacketReceiver
	void run();

	

};

class UDPClientSocket : public Socket {

public:

	static inline int packet_wait_micros = 5000; // microseconds to wait for a packet before checking the send queue

	//Open a UDP socket on the given port
	// Returns if successful
	bool connect(const std::string& ip, int port);

	// Send data through this socket
	// Returns if data seems to have sent (we can't know now if it arrived)
	bool send(int receiver_id, const std::vector<char>& data) override;

	// close all connections in this socket and stop allowing new ones if applicable
	void close() override;

	//Set the object that will get packets when they are sent to this socket
	void setPacketReceiver(PacketReceiver* receiver) override;

	~UDPClientSocket();

private:

	std::shared_ptr<SOCKET> socket_fd; // SOCKET cast to intptr_t to avoid including winsock
	int server_id = 0 ; //current server id, could change if closed and opened again
	std::shared_ptr<sockaddr_in> server_address;// always a sockaddr_in but can'rt include winsock in the .h or it breaks ALOT
	std::string server_ip ;
	int port = 0 ;
	PacketReceiver* packet_receiver = nullptr;

	std::thread thread; // nonblocking socket has its own thread to wait for any packets
	std::recursive_mutex lock; // used to protect against modifying the socket while packets are being received
	bool stop = false; // tells the thread to stop at the next chance
	std::queue<PendingPacket> send_queue;
	char buffer[32768] = {};
	
	// asynchronous method to catch packets and deliver them to PacketReceiver
	void run();

};




class TCPServerSocket : public Socket {
public:
	class Client{
	public:
		bool stop = false ;
		TCPServerSocket* parent = nullptr;
		int id = -1;
		SOCKET socket;
		std::thread thread; //each client has its own socket where we wait for packets from that socket
		std::thread send_thread; //each client has a separate thread to do nonblock duplex sends
		std::condition_variable cv; // condition vriable allows waking send thread only when there'ssomething to send

		Client(int my_id, const SOCKET& my_socket, TCPServerSocket* my_parent);

		Client(); // default constructor so it can be in a map

		void queueSend(const std::vector<char>& data) ;
		
	private:
		char buffer[32000] = {};
		int32_t packet_size = -1;// size of currently incoming packet
		std::vector<char> packet ; //packet currently being received
		
		std::mutex lock ; // lock for send queue
		std::queue<std::shared_ptr<std::vector<char>>> send_queue;
		std::mutex signal_lock; // lock for the condition variable
		
		bool send(const std::vector<char>& data);

		void run(); // runs the thread for this recieving for this client
		void runSend(); // runs the thread for sending for this client
	};

	TCPServerSocket();

	//Open a TCP socket on the given port
	// Returns if apparently successful
	bool open(int port);

	// Send data through this socket, nonblocking
	// Returns if data seems to have sent (we can't know now if it arrived)
	bool send(int receiver_id, const std::vector<char>& data) override;

	// close all connections in this socket and stop allowing new ones if applicable
	void close() override;

	//Set the object that will get packets when they are sent to this socket
	void setPacketReceiver(PacketReceiver* receiver) override;

	~TCPServerSocket();

private:
	SOCKET socket; // socket used ot listen for new connections
	int port = 0;
	std::map<int, std::shared_ptr<Client>> clients; // connection id -> client address
	std::thread thread; // nonblocking socket has its own thread to wait for connections
	std::recursive_mutex lock; // used to protect against modifying the socket while packets are being received
	bool stop = false; // tells the thread to stop at the next chance
	int next_client_id = 1;
	
	PacketReceiver* packet_receiver = nullptr;

	// asynchronous method to catch new connections
	void run();



};

class TCPClientSocket : public Socket {

public:

	TCPClientSocket();

	//Open a TCP socket on the given port connecting to a TCPServerSocket at the address
	// Returns if successful
	bool connect(const std::string& host, int port);

	// Send data through this socket
	// Returns if data seems to have sent (we can't know now if it arrived)
	bool send(int receiver_id, const std::vector<char>& data) override;

	// close all connections in this socket and stop allowing new ones if applicable
	void close() override;

	//Set the object that will get packets when they are sent to this socket
	void setPacketReceiver(PacketReceiver* receiver) override;

	~TCPClientSocket();

private:
	SOCKET socket ; // SOCKET cast to intptr_t to avoid including winsock
	int server_id = 0; //current server id, could change if closed and opened again
	std::shared_ptr<sockaddr_in> server_address;// always a sockaddr_in but can'rt include winsock in the .h or it breaks ALOT
	std::string server_ip;
	int port = 0;
	PacketReceiver* packet_receiver = nullptr;
	std::thread thread; // nonblocking socket has its own thread to wait for any packets
	std::recursive_mutex lock; // used to protect against modifying the socket while packets are being received
	bool stop = false; // tells the thread to stop at the next chance
	char buffer[32000] = {};
	int32_t packet_size = -1;// size of currently incoming packet
	std::vector<char> packet; //packet currently being received

	// asynchronous method to catch packets and deliver them to PacketReceiver
	void run();

};

#endif // #ifndef _SOCKETS_H_